### ISSUE TITLE
안돼요!!!!!!

### ISSUE THREAD

**Issue by ghost** [lilymaniac/Guide#2]
가이드 넘 잘쓰고 있었는데........
안돼요!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by ghost** [comment]
rul 줄임

https://goo.gl/97ERuZ

**Comment by ghost** [comment]
...

**Comment by lilymaniac** [comment]
도움이 되었다는 말씀은 고맙습니다.
근데 이슈 페이지에다 스팸하신다고 달라질 건 없어요. 이슈 닫았다고 '...' 라니요.

저는 4월에 3DS 처분했고, 그 후부터 어제까지는 기기도 없는 채로 페이지 관리했습니다.
1월 1일부터 어제까지 딱 5개월 관리하면서 얻은 거라고는 광고수입 3달러랑 일주일에 한두개씩 날아오는 욕/징징글밖에 없어요.

뭐 제가 대단한 일을 한 것도 아니지만 4월까지는 제가 사용하는 기계니까 욕 처먹으면서라도 별 생각 없이 유지보수했는데 기계 정리하고 나니까 공짜로 욕 받아먹는 페이지밖에 안되더라구요.

죄송하지만 다시 열 생각은 없습니다. 양해 부탁드려요.
페이지에 써 놓았듯이 backup-170601 브랜치에서 번역문을 가져다가 translate.3ds.guide 에다가 옮기셔도 되고, 포크하신 후에 개인 페이지 발행하셔도 됩니다.

이 이슈는 그냥 열어두겠습니다. 나중에 생각이 바뀌면 직접 닫아주세요.

**Comment by ghost** [comment]
네

**Comment by ghost** [comment]
그거 어떻게하는거에요
